server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /css/ {
        try_files $uri =404;
    }

    location /js/ {
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
