version: "3"
services:
  postgres:
    build: ./postgres
    ports:
      - "5433:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  fastapi_app:
    build: ./src
    ports:
      - "8000:80"
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  postgres_data:
